site_name: Concourse Docs
site_url: https://concourse-ci.org/

repo_url: https://github.com/kcbimonte/concourse-docs
repo_name: kbimonte/concourse-docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

theme:
  name: material
  features:
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - navigation.footer

  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Concourse: index.md
  - Docs:
      - docs/index.md
      - Getting Started:
          - docs/getting-started/index.md
          - Quick Start: docs/getting-started/quick-start.md
          - Hello World Pipeline: docs/getting-started/hello-world.md
          - Inputs and Outputs: docs/getting-started/inputs-outputs.md
          - Resources: docs/getting-started/resources.md
  - Examples: examples/index.md
  - Project: project/index.md
  - Ecosystem: ecosystem/index.md
  - Support: support/index.md