site_name: Concourse Docs
site_url: https://concourse-ci.org/

repo_url: https://github.com/kcbimonte/concourse-docs
repo_name: kbimonte/concourse-docs

plugins:
  - search
  - blog:
      blog_dir: blog
      post_url_date_format: yyyy-MM-dd
      post_url_format: "{date}-{slug}"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

theme:
  name: material
  #  custom_dir: overrides
  features:
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - navigation.footer

  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Concourse: index.md
  - Docs:
      - docs/index.md
      - Getting Started:
          - docs/getting-started/index.md
          - Quick Start: docs/getting-started/quick-start.md
          - Hello World Pipeline: docs/getting-started/hello-world.md
          - Inputs and Outputs: docs/getting-started/inputs-outputs.md
          - Resources: docs/getting-started/resources.md
      - Install:
          - docs/install/index.md
      - Auth & Teams:
          - docs/auth-and-teams/index.md
      - The fly CLI:
          - docs/fly/index.md
      - Config Basics:
          - docs/config-basics/index.md
      - Pipelines:
          - docs/pipelines/index.md
      - Vars:
          - docs/vars/index.md
      - Resources:
          - docs/resources/index.md
      - Resource Types:
          - docs/resource-types/index.md
      - Jobs:
          - docs/jobs/index.md
      - Steps:
          - docs/steps/index.md
      - Tasks:
          - docs/tasks/index.md
      - Builds:
          - docs/builds/index.md
      - How-To Guides:
          - docs/how-to/index.md
      - Operation:
          - docs/operation/index.md
      - Observation:
          - docs/observation/index.md
      - Internals:
          - docs/internals/index.md
  - Examples:
      - examples/index.md
      - Hello World pipeline: examples/hello-world.md
      - Serial job example: examples/serial-job.md
      - Pipeline ((vars)) example: examples/pipeline-vars.md
      - Set Pipeline Example: examples/set-pipeline.md
      - Task inputs and outputs example: examples/inputs-outputs.md
      - time-triggered job example: examples/time-triggered.md
      - git-triggered job example: examples/git-triggered.md
      - Manually triggered job example: examples/manually-triggered.md
      - Job & task hooks example: examples/job-and-task-hooks.md
      - Golang library testing example: examples/golang-lib.md
      - Rails application testing example: examples/rails-app.md
      - Java application testing example: examples/java-app.md
      - Nodejs application testing example: examples/nodejs-app.md
      - PHP application testing example: examples/php-app.md
  - Project: project/index.md
  - Ecosystem: ecosystem/index.md
  - Support: support/index.md
  - Blog:
      - blog/index.md